package HDMRORDERS.CP630.HIBERNATE;
// Generated Dec 18, 2020 3:25:44 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Items generated by hbm2java
 */
public class Items implements java.io.Serializable {

	private Integer id;
	private int productId;
	private String productName;
	private Integer quantity;
	private String comments;
	private Date sysDate;
	private Set orderses = new HashSet(0);

	public Items() {
	}

	public Items(int productId, Date sysDate) {
		this.productId = productId;
		this.sysDate = sysDate;
	}

	public Items(int productId, String productName, Integer quantity, String comments, Date sysDate, Set orderses) {
		this.productId = productId;
		this.productName = productName;
		this.quantity = quantity;
		this.comments = comments;
		this.sysDate = sysDate;
		this.orderses = orderses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public Date getSysDate() {
		return this.sysDate;
	}

	public void setSysDate(Date sysDate) {
		this.sysDate = sysDate;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

}
