package HDMRORDERS.CP630.HIBERNATE;
// Generated Dec 18, 2020 3:25:44 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Orders generated by hbm2java
 */

@Entity
public class Orders implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	private Items items;
	private String orderNum;
	private Float unitPrice;
	private Integer quantity;
	private Float balance;
	private Float shipping;
	private Float salesPrice;
	private Float subtotal;
	private Float grossIncome;
	private Date transactionDate;
	private Date sysDate;

	public Orders() {
	}

	public Orders(Date transactionDate, Date sysDate) {
		this.transactionDate = transactionDate;
		this.sysDate = sysDate;
	}

	public Orders(Items items, String orderNum, Float unitPrice, Integer quantity, Float balance, Float shipping,
			Float salesPrice, Float subtotal, Float grossIncome, Date transactionDate, Date sysDate) {
		this.items = items;
		this.orderNum = orderNum;
		this.unitPrice = unitPrice;
		this.quantity = quantity;
		this.balance = balance;
		this.shipping = shipping;
		this.salesPrice = salesPrice;
		this.subtotal = subtotal;
		this.grossIncome = grossIncome;
		this.transactionDate = transactionDate;
		this.sysDate = sysDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	public String getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(String orderNum) {
		this.orderNum = orderNum;
	}

	public Float getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(Float unitPrice) {
		this.unitPrice = unitPrice;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Float getBalance() {
		return this.balance;
	}

	public void setBalance(Float balance) {
		this.balance = balance;
	}

	public Float getShipping() {
		return this.shipping;
	}

	public void setShipping(Float shipping) {
		this.shipping = shipping;
	}

	public Float getSalesPrice() {
		return this.salesPrice;
	}

	public void setSalesPrice(Float salesPrice) {
		this.salesPrice = salesPrice;
	}

	public Float getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(Float subtotal) {
		this.subtotal = subtotal;
	}

	public Float getGrossIncome() {
		return this.grossIncome;
	}

	public void setGrossIncome(Float grossIncome) {
		this.grossIncome = grossIncome;
	}

	public Date getTransactionDate() {
		return this.transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	public Date getSysDate() {
		return this.sysDate;
	}

	public void setSysDate(Date sysDate) {
		this.sysDate = sysDate;
	}

}
