package HDMRORDERS.PORTAL4.DOMAIN;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Items generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "items", catalog = "db_orders", uniqueConstraints = @UniqueConstraint(columnNames = "product_id"))
public class Items implements java.io.Serializable {

	private Integer id;
	private int productId;
	private String productName;
	private Integer quantity;
	private String comments;
	private Date sysDate;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Items() {
	}

	public Items(int productId, Date sysDate) {
		this.productId = productId;
		this.sysDate = sysDate;
	}

	public Items(int productId, String productName, Integer quantity, String comments, Date sysDate, Set<Orders> orderses) {
		this.productId = productId;
		this.productName = productName;
		this.quantity = quantity;
		this.comments = comments;
		this.sysDate = sysDate;
		this.orderses = orderses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "product_id", unique = true, nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "product_name")
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "comments", length = 1000)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sys_date", nullable = false, length = 19)
	public Date getSysDate() {
		return this.sysDate;
	}
	
	public void setSysDate(Date sysDate) {
		this.sysDate = sysDate;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "items")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}